// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOiGIthqnPMZUUbwFMEKCmuxw5e1FbpxM',
    appId: '1:913008264557:web:219a0f8a763d6216bf8664',
    messagingSenderId: '913008264557',
    projectId: 'koofy-sudoku',
    authDomain: 'koofy-sudoku.firebaseapp.com',
    storageBucket: 'koofy-sudoku.firebasestorage.app',
    measurementId: 'G-9D8TXZJJZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC80ZQNiAIqfWBmRVakAyXw_6yuRn4Fsk4',
    appId: '1:913008264557:android:54765182b84ade98bf8664',
    messagingSenderId: '913008264557',
    projectId: 'koofy-sudoku',
    storageBucket: 'koofy-sudoku.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO2GIEWfXWuQxC2dKgEDR4_obRBESrPe0',
    appId: '1:913008264557:ios:726561e468a4f4c4bf8664',
    messagingSenderId: '913008264557',
    projectId: 'koofy-sudoku',
    storageBucket: 'koofy-sudoku.firebasestorage.app',
    androidClientId: '913008264557-caske1i5j5ga7puhvghgop9i2m59r4h5.apps.googleusercontent.com',
    iosClientId: '913008264557-21gthroe1gp7ceqbkhai86jrtrhar8oa.apps.googleusercontent.com',
    iosBundleId: 'com.example.sudokuFlutter',
  );
}
